export type StateSEO = {
  slug: string;
  name: string;
  abbr: string;
  region: string;
  description: string;
  keyTopics: string[];
  officeFocus: string;
};

export const states: StateSEO[] = [
  { slug: "alabama", name: "Alabama", abbr: "AL", region: "South", description: "Social Security retirement, SSDI, SSI, and Medicare planning guidance for Alabama residents.", keyTopics: ["Social Security in Alabama", "Medicare in Alabama", "SSDI eligibility Alabama", "SSA office locator Alabama"], officeFocus: "Find local Social Security office details and benefit-planning guidance in Alabama." },
  { slug: "alaska", name: "Alaska", abbr: "AK", region: "West", description: "Benefit rules, claim timing, and Medicare details for Alaska residents seeking Social Security guidance.", keyTopics: ["Social Security in Alaska", "Medicare in Alaska", "retirement benefits Alaska", "benefit tax Alaska"], officeFocus: "Review Alaska SSA office information and claim strategy guidance for retirement and disability benefits." },
  { slug: "arizona", name: "Arizona", abbr: "AZ", region: "West", description: "Arizona Social Security guidance covering retirement, survivors, and healthcare decisions for residents.", keyTopics: ["Social Security in Arizona", "Arizona Medicare", "retirement age Arizona", "benefits estimator Arizona"], officeFocus: "Explore Arizona claim timing, Medicare, and local office planning resources." },
  { slug: "arkansas", name: "Arkansas", abbr: "AR", region: "South", description: "Arkansas-focused Social Security education, disability help, and Medicare planning for retirees and families.", keyTopics: ["Social Security in Arkansas", "SSDI Arkansas", "Medicare Arkansas", "survivor benefits Arkansas"], officeFocus: "Understand Arkansas SSA resources and how to prepare for retirement or disability claims." },
  { slug: "california", name: "California", abbr: "CA", region: "West", description: "California Social Security advice for retirement, disability, spousal benefits, and local claim questions.", keyTopics: ["Social Security in California", "California Medicare", "SSDI California", "Social Security office California"], officeFocus: "Find California benefit guides, office details, and state-specific claiming strategies." },
  { slug: "colorado", name: "Colorado", abbr: "CO", region: "West", description: "Colorado residents can compare retirement ages, Medicare enrollment, and disability requirements with clear planning guidance.", keyTopics: ["Social Security in Colorado", "Colorado retirement benefits", "Medicare Colorado", "SSI Colorado"], officeFocus: "Learn how to navigate Colorado Social Security resources and local office support." },
  { slug: "connecticut", name: "Connecticut", abbr: "CT", region: "Northeast", description: "Connecticut Social Security information for retirees, workers, and families planning for healthcare and claiming decisions.", keyTopics: ["Social Security in Connecticut", "benefits estimator Connecticut", "Medicare Connecticut", "spousal benefits Connecticut"], officeFocus: "Use Connecticut Social Security guidance to estimate benefits, filing timing, and office support." },
  { slug: "delaware", name: "Delaware", abbr: "DE", region: "South", description: "Delaware Social Security and Medicare planning for retirement, survivor, and disability decision-making.", keyTopics: ["Social Security in Delaware", "Medicare Delaware", "SSDI Delaware", "retirement planning Delaware"], officeFocus: "Review Delaware claim rules, cost planning, and local SSA support options." },
  { slug: "florida", name: "Florida", abbr: "FL", region: "South", description: "Florida Social Security and Medicare planning guidance for retirees, workers, and people preparing for claim decisions.", keyTopics: ["Social Security in Florida", "Florida Medicare", "retirement benefits Florida", "SSI Florida"], officeFocus: "Understand Florida claim timing, local offices, and Medicare costs for retirees." },
  { slug: "georgia", name: "Georgia", abbr: "GA", region: "South", description: "Georgia Social Security guidance for retirement benefits, disability, and benefit tax questions.", keyTopics: ["Social Security in Georgia", "Georgia SSDI", "Medicare Georgia", "benefit tax Georgia"], officeFocus: "Plan around Georgia SSA rules, disability claims, and Medicare enrollment windows." },
  { slug: "hawaii", name: "Hawaii", abbr: "HI", region: "West", description: "Hawaii-specific Social Security guidance for retirement, disability, and healthcare planning.", keyTopics: ["Social Security in Hawaii", "Medicare Hawaii", "retire in Hawaii Social Security", "benefits Hawaii"], officeFocus: "Review Hawaii benefit planning and local SSA office navigation resources." },
  { slug: "idaho", name: "Idaho", abbr: "ID", region: "West", description: "Idaho Social Security advice for retirement, spousal claims, and local office access.", keyTopics: ["Social Security in Idaho", "Medicare Idaho", "retirement age Idaho", "spousal benefits Idaho"], officeFocus: "Learn about Idaho claim decisions, local offices, and Medicare coverage planning." },
  { slug: "illinois", name: "Illinois", abbr: "IL", region: "Midwest", description: "Illinois Social Security guidance covering retirement, survivor, spousal, and tax planning questions.", keyTopics: ["Social Security in Illinois", "Illinois Medicare", "SSDI Illinois", "benefits tax Illinois"], officeFocus: "Find Illinois-focused guidance on claim timing, SSDI, and local office details." },
  { slug: "indiana", name: "Indiana", abbr: "IN", region: "Midwest", description: "Indiana residents can better understand claiming age, benefits taxes, and retirement planning with expert guidance.", keyTopics: ["Social Security in Indiana", "Indiana retirement", "SSDI Indiana", "benefits tax Indiana"], officeFocus: "Use Indiana claim planning resources to compare filing strategies and local support." },
  { slug: "iowa", name: "Iowa", abbr: "IA", region: "Midwest", description: "Iowa guidance for Social Security retirement benefits, SSDI, disability rules, and Medicare planning.", keyTopics: ["Social Security in Iowa", "Medicare Iowa", "SSDI Iowa", "retirement benefits Iowa"], officeFocus: "Review Iowa Social Security office and planning information for retirement or disability claims." },
  { slug: "kansas", name: "Kansas", abbr: "KS", region: "Midwest", description: "Kansas Social Security education for retirement benefits, disability claims, and healthcare planning.", keyTopics: ["Social Security in Kansas", "Kansas Medicare", "SSI Kansas", "retirement age Kansas"], officeFocus: "Find Kansas-oriented Social Security guidance and local office resources." },
  { slug: "kentucky", name: "Kentucky", abbr: "KY", region: "South", description: "Kentucky benefit planning guidance covering SSDI, retirement claims, and Medicare enrollment decisions.", keyTopics: ["Social Security in Kentucky", "Kentucky Medicare", "SSDI Kentucky", "survivor benefits Kentucky"], officeFocus: "Prepare for Kentucky SSA support and understand local benefit-planning strategies." },
  { slug: "louisiana", name: "Louisiana", abbr: "LA", region: "South", description: "Louisiana Social Security information on retirement, disability, and Medicare support for local families.", keyTopics: ["Social Security in Louisiana", "Medicare Louisiana", "retirement Louisiana", "SSDI Louisiana"], officeFocus: "Explore Louisiana retirement and disability planning with local office guidance." },
  { slug: "maine", name: "Maine", abbr: "ME", region: "Northeast", description: "Maine Social Security resource page for retirement, claim strategy, and local office support.", keyTopics: ["Social Security in Maine", "Maine Medicare", "retired benefits Maine", "SSA office Maine"], officeFocus: "Review Maine Social Security and Medicare guidance for local planning needs." },
  { slug: "maryland", name: "Maryland", abbr: "MD", region: "South", description: "Maryland Social Security guidance for benefits planning, claims, and Medicare-related decisions.", keyTopics: ["Social Security in Maryland", "Maryland Medicare", "SSDI Maryland", "benefits estimator Maryland"], officeFocus: "Understand Maryland benefit strategies and local office support before filing." },
  { slug: "massachusetts", name: "Massachusetts", abbr: "MA", region: "Northeast", description: "Massachusetts Social Security guidance for retirement age, survivor benefits, and Medicare decisions.", keyTopics: ["Social Security in Massachusetts", "Massachusetts Medicare", "benefits tax Massachusetts", "retirement Massachusetts"], officeFocus: "Use Massachusetts Social Security guidance to compare claim timing and local office support." },
  { slug: "michigan", name: "Michigan", abbr: "MI", region: "Midwest", description: "Michigan Social Security planning resources for retirement, SSDI, and healthcare needs.", keyTopics: ["Social Security in Michigan", "Medicare Michigan", "SSDI Michigan", "retirement age Michigan"], officeFocus: "Review Michigan local benefits guidance and office access information." },
  { slug: "minnesota", name: "Minnesota", abbr: "MN", region: "Midwest", description: "Minnesota planning resources for Social Security retirement, taxes, and Medicare decisions.", keyTopics: ["Social Security in Minnesota", "Minnesota Medicare", "benefit tax Minnesota", "SSA office Minnesota"], officeFocus: "Learn about Minnesota Social Security help, local office resources, and filing decisions." },
  { slug: "mississippi", name: "Mississippi", abbr: "MS", region: "South", description: "Mississippi Social Security guidance for retirement, disability, and local office questions.", keyTopics: ["Social Security in Mississippi", "Mississippi Medicare", "SSDI Mississippi", "retirement planning Mississippi"], officeFocus: "Get Mississippi claim strategy and local office information for benefit planning." },
  { slug: "missouri", name: "Missouri", abbr: "MO", region: "Midwest", description: "Missouri Social Security planning guidance for retirement, survivor, and healthcare decisions.", keyTopics: ["Social Security in Missouri", "Missouri Medicare", "survivor benefits Missouri", "benefits estimator Missouri"], officeFocus: "Prepare for Missouri retirement or disability decisions with clear benefit guidance." },
  { slug: "montana", name: "Montana", abbr: "MT", region: "West", description: "Montana resident guidance for retirement, disability benefits, and local SSA support.", keyTopics: ["Social Security in Montana", "Medicare Montana", "SSI Montana", "retirement Montana"], officeFocus: "Find Montana Social Security and office resource guidance for claim planning." },
  { slug: "nebraska", name: "Nebraska", abbr: "NE", region: "Midwest", description: "Nebraska Social Security guidance covering retirement planning, benefits taxes, and Medicare decisions.", keyTopics: ["Social Security in Nebraska", "Nebraska Medicare", "benefits tax Nebraska", "retirement Nebraska"], officeFocus: "Navigate Nebraska claim timing and local SSA support for retirement planning." },
  { slug: "nevada", name: "Nevada", abbr: "NV", region: "West", description: "Nevada Social Security guidance for retirement age decisions, disability claims, and healthcare coverage.", keyTopics: ["Social Security in Nevada", "Nevada Medicare", "retirement benefits Nevada", "SSDI Nevada"], officeFocus: "Compare Nevada retirement benefits and local office information before filing." },
  { slug: "new-hampshire", name: "New Hampshire", abbr: "NH", region: "Northeast", description: "New Hampshire guidance for Social Security claim timing, survivor benefits, and local office access.", keyTopics: ["Social Security in New Hampshire", "New Hampshire Medicare", "retirement age New Hampshire", "benefits tax New Hampshire"], officeFocus: "Review New Hampshire claim timing and benefits support resources." },
  { slug: "new-jersey", name: "New Jersey", abbr: "NJ", region: "Northeast", description: "New Jersey Social Security and Medicare planning for retirement, spousal claims, and disability support.", keyTopics: ["Social Security in New Jersey", "Medicare New Jersey", "SSDI New Jersey", "Social Security office New Jersey"], officeFocus: "Get practical New Jersey claim guidance and office preparation tips." },
  { slug: "new-mexico", name: "New Mexico", abbr: "NM", region: "West", description: "New Mexico Social Security guidance for benefits planning, claim timing, and healthcare decisions.", keyTopics: ["Social Security in New Mexico", "Medicare New Mexico", "retirement benefits New Mexico", "SSI New Mexico"], officeFocus: "Use New Mexico claim planning resources to compare retirement and disability options." },
  { slug: "new-york", name: "New York", abbr: "NY", region: "Northeast", description: "New York Social Security education for retirement, spousal, and Medicare planning across major local markets.", keyTopics: ["Social Security in New York", "New York Medicare", "SSDI New York", "retirement age New York"], officeFocus: "Review New York benefits strategy and local office findings for claim preparation." },
  { slug: "north-carolina", name: "North Carolina", abbr: "NC", region: "South", description: "North Carolina Social Security guidance for local retirees, families, and people evaluating healthcare and disability benefits.", keyTopics: ["Social Security in North Carolina", "Medicare North Carolina", "SSDI North Carolina", "benefits tax North Carolina"], officeFocus: "Plan for North Carolina Social Security and local office support with practical guidance." },
  { slug: "north-dakota", name: "North Dakota", abbr: "ND", region: "Midwest", description: "North Dakota retirement planning and Social Security benefit guidance for a straightforward claim strategy.", keyTopics: ["Social Security in North Dakota", "North Dakota Medicare", "retirement benefits North Dakota", "SSA office North Dakota"], officeFocus: "Review North Dakota benefit guidance and office details before filing." },
  { slug: "ohio", name: "Ohio", abbr: "OH", region: "Midwest", description: "Ohio Social Security resources for retirement, disability, and local benefits planning decisions.", keyTopics: ["Social Security in Ohio", "Medicare Ohio", "SSDI Ohio", "benefits estimator Ohio"], officeFocus: "Understand Ohio scheduling, benefits planning, and office access information." },
  { slug: "oklahoma", name: "Oklahoma", abbr: "OK", region: "South", description: "Oklahoma Social Security planning guidance for retirement, disability claims, and Medicare choices.", keyTopics: ["Social Security in Oklahoma", "Oklahoma Medicare", "SSI Oklahoma", "retirement age Oklahoma"], officeFocus: "Find Oklahoma claim planning guidance and steps to prepare for a local SSA office visit." },
  { slug: "oregon", name: "Oregon", abbr: "OR", region: "West", description: "Oregon Social Security guidance for retirement timing, Medicare, and disability rules.", keyTopics: ["Social Security in Oregon", "Medicare Oregon", "retirement Oregon", "benefit taxes Oregon"], officeFocus: "Review Oregon-specific plan guidance and local office support before applying." },
  { slug: "pennsylvania", name: "Pennsylvania", abbr: "PA", region: "Northeast", description: "Pennsylvania benefits education for retirement, survivor claims, and healthcare planning.", keyTopics: ["Social Security in Pennsylvania", "Pennsylvania Medicare", "SSDI Pennsylvania", "survivor benefits Pennsylvania"], officeFocus: "Use Pennsylvania Social Security guidance to compare claim strategies and office support." },
  { slug: "rhode-island", name: "Rhode Island", abbr: "RI", region: "Northeast", description: "Rhode Island Social Security and Medicare guidance focused on retirement benefits and enrollment planning.", keyTopics: ["Social Security in Rhode Island", "Medicare Rhode Island", "retirement age Rhode Island", "benefits estimator Rhode Island"], officeFocus: "Review Rhode Island claim planning resources and local benefit support options." },
  { slug: "south-carolina", name: "South Carolina", abbr: "SC", region: "South", description: "South Carolina Social Security guidance covering retirement, disability, survivor benefits, and Medicare decisions.", keyTopics: ["Social Security in South Carolina", "South Carolina Medicare", "SSDI South Carolina", "benefit tax South Carolina"], officeFocus: "Understand how South Carolina residents can plan claims and contact local SSA offices." },
  { slug: "south-dakota", name: "South Dakota", abbr: "SD", region: "Midwest", description: "South Dakota Social Security and Medicare guidance for retirement claims and benefits planning.", keyTopics: ["Social Security in South Dakota", "Medicare South Dakota", "retirement South Dakota", "SSA office South Dakota"], officeFocus: "Prepare for South Dakota Social Security support and local claim guidance." },
  { slug: "tennessee", name: "Tennessee", abbr: "TN", region: "South", description: "Tennessee retirement and Social Security resources for benefit planning, disability claims, and Medicare coverage.", keyTopics: ["Social Security in Tennessee", "Medicare Tennessee", "benefits estimator Tennessee", "SSDI Tennessee"], officeFocus: "Review Tennessee benefit strategy and local office support prior to filing." },
  { slug: "texas", name: "Texas", abbr: "TX", region: "South", description: "Texas-focused Social Security planning for retirement benefits, disability steps, Medicare, and survivor coverage.", keyTopics: ["Social Security in Texas", "Texas Medicare", "SSDI Texas", "Social Security office Texas"], officeFocus: "Find Texas Social Security office and benefits guidance for retirement and disability planning." },
  { slug: "utah", name: "Utah", abbr: "UT", region: "West", description: "Utah Social Security guidance for retirement income, disability claims, and Medicare enrollment.", keyTopics: ["Social Security in Utah", "Medicare Utah", "benefits tax Utah", "SSDI Utah"], officeFocus: "Learn Utah-specific claim timing and office preparation guidance." },
  { slug: "vermont", name: "Vermont", abbr: "VT", region: "Northeast", description: "Vermont Social Security planning guidance for local claim decisions and Medicare-ready retirement strategies.", keyTopics: ["Social Security in Vermont", "Medicare Vermont", "retirement Vermont", "benefits estimator Vermont"], officeFocus: "Understand Vermont Social Security planning and local office support options." },
  { slug: "virginia", name: "Virginia", abbr: "VA", region: "South", description: "Virginia Social Security information for benefit claims, survivor support, and Medicare planning decisions.", keyTopics: ["Social Security in Virginia", "Virginia Medicare", "SSDI Virginia", "spousal benefits Virginia"], officeFocus: "Use Virginia benefit guidance to review claim timing and local office planning resources." },
  { slug: "washington", name: "Washington", abbr: "WA", region: "West", description: "Washington Social Security guidance for retirement, disability, and claim timing with local office awareness.", keyTopics: ["Social Security in Washington", "Washington Medicare", "SSDI Washington", "benefits estimator Washington"], officeFocus: "Review Washington claim timing, local SSA office support, and benefits planning resources." },
  { slug: "west-virginia", name: "West Virginia", abbr: "WV", region: "South", description: "West Virginia Social Security guidance for disability, retirement, and Medicare planning across the state.", keyTopics: ["Social Security in West Virginia", "Medicare West Virginia", "SSI West Virginia", "retirement age West Virginia"], officeFocus: "Understand West Virginia Social Security rules and near-you support resources." },
  { slug: "wisconsin", name: "Wisconsin", abbr: "WI", region: "Midwest", description: "Wisconsin Social Security planning resources for retirement benefits, survivor claims, and benefit taxes.", keyTopics: ["Social Security in Wisconsin", "Medicare Wisconsin", "benefits tax Wisconsin", "survivor benefits Wisconsin"], officeFocus: "Review Wisconsin retirement and Medicare guidance with local office preparation tips." },
  { slug: "wyoming", name: "Wyoming", abbr: "WY", region: "West", description: "Wyoming Social Security guidance for retirees comparing claim timing, disability support, and local office access.", keyTopics: ["Social Security in Wyoming", "Wyoming Medicare", "retirement age Wyoming", "benefit tax Wyoming"], officeFocus: "Get Wyoming Social Security planning guidance and office access information." },
];

export function getStateBySlug(slug: string) {
  return states.find((state) => state.slug === slug.toLowerCase());
}

export function getStateByName(name: string) {
  return states.find((state) => state.name.toLowerCase() === name.toLowerCase());
}
