import { ArrowLeft, Info } from "lucide-react"
import Link from "next/link"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Disclaimer — Social Security Guide",
  description: "Important disclaimers about Social Security Guide information and calculator estimates.",
  openGraph: {
    title: "Disclaimer — Social Security Guide",
    description: "Important disclaimers about Social Security Guide information and calculator estimates.",
    url: "https://www.socialsecurityguidecalc.com/disclaimer",
  },
}

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Disclaimer",
  url: "https://www.socialsecurityguidecalc.com/disclaimer",
  description: "Disclaimers for Social Security Guide information and calculator estimates.",
  publisher: { "@type": "Organization", name: "Social Security Guide", url: "https://www.socialsecurityguidecalc.com" },
}

export default function DisclaimerPage() {
  return (
    <div className="bg-slate-50 min-h-screen">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <header className="bg-[#071530] py-14 text-white border-b border-white/10">
        <div className="container-site max-w-3xl mx-auto px-4">
          <Link href="/" className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-300 hover:text-[#e4b325] transition-colors mb-4 group">
            <ArrowLeft size={14} className="transition-transform group-hover:-translate-x-1" /> Back to Home
          </Link>
          <span className="block text-xs font-bold text-[#e4b325] uppercase tracking-wider mb-2">Legal &amp; Security</span>
          <h1 className="text-3xl sm:text-4xl font-bold font-playfair text-white mb-3">Disclaimer</h1>
          <p className="text-slate-300 text-xs sm:text-sm">Last updated: August 25, 2026</p>
        </div>
      </header>

      <main className="container-site max-w-3xl mx-auto px-4 py-12">
        <article className="bg-white border border-slate-200/80 rounded-2xl p-6 sm:p-10 shadow-xs">
          <div className="bg-blue-50/80 border border-blue-100 rounded-xl p-4 mb-8 flex gap-3 items-start">
            <Info size={18} className="text-blue-700 mt-0.5 flex-shrink-0" />
            <p className="text-xs sm:text-sm text-slate-800 leading-relaxed font-medium m-0">Please read this Disclaimer carefully before using Our Service.</p>
          </div>
          <div className="prose-article max-w-none">

<h2>Interpretation and Definitions</h2>
<h3>Interpretation</h3>
<p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

<h3>Definitions</h3>
<p>For the purposes of this Disclaimer:</p>
<ul>
  <li><p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Disclaimer) refers to Social Security Guide.</p></li>
  <li><p><strong>Service</strong> refers to the Website.</p></li>
  <li><p><strong>You</strong> means the individual accessing the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p></li>
  <li><p><strong>Website</strong> refers to Social Security Guide, accessible from <a href="https://www.socialsecurityguidecalc.com/" rel="noopener noreferrer" target="_blank">https://www.socialsecurityguidecalc.com/</a>.</p></li>
</ul>

<h2>Government Non-Affiliation Disclaimer</h2>
<p>Social Security Guide is an independent educational website and is NOT affiliated with, authorized by, endorsed by, or in any way officially connected with the U.S. Social Security Administration (SSA), Medicare, or any other government agency.</p>

<h2>General Disclaimer & Calculator Estimates</h2>
<p>The information contained on the Service and outputs generated by calculators are for general educational purposes only. The Company assumes no responsibility for errors or omissions in the contents of the Service.</p>
<p>In no event shall the Company be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
<p>The Company does not warrant that the Service is free of viruses or other harmful components.</p>

<h2>External Links Disclaimer</h2>
<p>The Service may contain links to external websites that are not provided or maintained by or in any way affiliated with the Company. Please note that the Company does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.</p>

<h2>Errors and Omissions Disclaimer</h2>
<p>The information given by the Service is for general guidance on matters of interest only. Even if the Company takes every precaution to ensure that the content of the Service is both current and accurate, errors can occur. Plus, given the changing nature of laws, rules and regulations, there may be delays, omissions or inaccuracies in the information contained on the Service.</p>
<p>The Company is not responsible for any errors or omissions, or for the results obtained from the use of this information.</p>

<h2>Fair Use Disclaimer</h2>
<p>The Company may use copyrighted material which has not always been specifically authorized by the copyright owner. The Company is making such material available for criticism, comment, news reporting, teaching, scholarship, or research.</p>
<p>The Company believes this constitutes a &quot;fair use&quot; of any such copyrighted material as provided for in section 107 of the United States Copyright law.</p>

<h2>No Professional Advice Disclaimer</h2>
<p>The information on the Service is provided with the understanding that the Company is not herein engaged in rendering legal, financial, tax, or other professional advice and services. As such, it should not be used as a substitute for consultation with professional accounting, tax, legal, or financial advisers.</p>

<h2>&quot;Use at Your Own Risk&quot; Disclaimer</h2>
<p>All information in the Service is provided &quot;as is&quot;, with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of this information, and without warranty of any kind, express or implied.</p>

<h2>Contact Us</h2>
<p>If you have any questions about this Disclaimer, You can contact Us:</p>
<ul>
  <li>By email: contact@socialsecurityguidecalc.com</li>
</ul>
          </div>
        </article>
      </main>
    </div>
  )
}